server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: c3VwZXItc2VjcmV0LWp3dC1zaWduaW5nLWtleS1mb3ItZGV2ZWxvcG1lbnQtZW52aXJvbm1lbnQtMjAyNg==
