spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_user_db
    username: root
    password: Manick@123

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8082

jwt:
  secret: c3VwZXItc2VjcmV0LWp3dC1zaWduaW5nLWtleS1mb3ItZGV2ZWxvcG1lbnQtZW52aXJvbm1lbnQtMjAyNg==
  expiration: 15m